var languageCodes = {

    {name : 'Afrikaans',
     tag : 'af'},
    {name : 'Albanian',
     tag : 'sq'},
    {name : 'Arabic',
     tag : 'ar'},
    {name : 'Armenian',
     tag : 'hy'},
    {name : 'Azerbaijani',
     tag : 'az'},
    {name : 'Basque',
     tag : 'eu'},
    {name : 'Belarusian',
     tag : 'be'},
    {name :' Bengali',
     tag : 'bn'},
    {name :' Bosnian',
     tag : 'bs'},
    {name : 'Bulgarian',
     tag : 'bg'},
    {name : 'Catalan',
     tag : 'ca'},
    {name : 'Cebuano',
     tag : 'ceb'},
    {name : 'Chichewa',
     tag : 'ny'},
    {name : 'Croatian',
     tag : 'hr'},
    {name : 'Czech',
     tag : 'cs'},
    {name : 'Danish ',
     tag    : 'da'},
    {name : 'Dutch',
     tag : 'nl'},
    {name : 'English ',
     tag    : 'en'},
    {name : 'Esperanto',
     tag : 'eo'},
    {name : 'Estonian',
     tag : 'et'},
    {name : 'Filipino',
     tag : 'tl'},
    {name : 'Finnish',
     tag : 'fi'},
    {name : 'French ',
     tag    : 'fr'},
    {name : 'Galician',
     tag : 'gl'},
    {name : 'Georgian ',
     tag    : 'ka'},
    {name : 'German ',
     tag    : 'de'},
    {name : 'Greek ',
     tag    : 'el'},
    {name : 'Gujarati ',
     tag    : 'gu'},
    {name : 'Haitian',
     tag : 'ht'},
    {name : 'Hausa ',
     tag    : 'ha'},
    {name : 'Hebrew',
     tag : 'iw'},
    {name : 'Hindi ',
     tag    : 'hi'},
    {name : 'Hmong',
     tag : 'hmn'},
    {name : 'Hungarian',
     tag : 'hu'},
    {name : 'Icelandic ',
     tag    : 'is'},
    {name : 'Igbo',
     tag : 'ig'},
    {name : 'Indonesian',
     tag : 'id'},
    {name : 'Irish',
     tag : 'ga'},
    {name : 'Italian',
     tag : 'it'},
    {name : 'Japanese',
     tag : 'ja'},
    {name : 'Javanese',
     tag : 'jw'},
    {name : 'Kannada',
     tag : 'kn'},
    {name : 'Kazakh',
     tag : 'kk'},
    {name : 'Khmer',
     tag : 'km'},
    {name : 'Korean',
     tag : 'ko'},
    {name : 'Lao',
     tag : 'lo'},
    {name : 'Latin ',
     tag    : 'la'},
    {name : 'Latvian',
     tag : 'lv'},
    {name : 'Lithuanian',
     tag : 'lt'},
    {name : 'Macedonian',
     tag : 'mk'},
    {name : 'Malagasy',
     tag : 'mg'},
    {name : 'Malay',
     tag : 'ms'},
    {name : 'Malayalam',
     tag : 'ml'},
    {name : 'Maltese',
     tag : 'mt'},
    {name : 'Maori',
     tag : 'mi'},
    {name : 'Marathi',
     tag : 'mr'},
    {name : 'Mongolian ',
     tag    : 'mn'},
    {name : 'Myanmar ',
     tag    : 'my'},
    {name : 'Nepali',
     tag : 'ne'},
    {name : 'Norwegian ',
     tag    : 'no'},
    {name : 'Persian',
     tag : 'fa'},
    {name : 'Polish',
     tag : 'pl'},
    {name : 'Portuguese',
     tag : 'pt'},
    {name : 'Punjabi ',
     tag    : 'ma'},
    {name : 'Romanian',
     tag : 'ro'},
    {name : 'Russian ',
     tag    : 'ru'},
    {name : 'Serbian',
     tag : 'sr'},
    {name : 'Sesotho',
     tag : 'st'},
    {name : 'Sinhala',
     tag : 'si'},
    {name : 'Slovak ',
     tag    : 'sk'},
    {name : 'Slovenian',
     tag : 'sl'},
    {name : 'Somali',
     tag : 'so'},
    {name : 'Spanish ',
     tag    : 'es'},
    {name : 'Sudanese',
     tag : 'su'},
    {name : 'Swahili',
     tag : 'sw'},
    {name : 'Swedish',
     tag : 'sv'},
    {name : 'Tajik',
     tag : 'tg'},
    {name : 'Tamil',
     tag : 'ta'},
    {name : 'Telugu',
     tag : 'te'},
    {name : 'Thai',
     tag : 'th'},
    {name : 'Turkish',
     tag : 'tr'},
    {name : 'Ukrainian',
     tag : 'uk'},
    {name : 'Urdu',
     tag : 'ur'},
    {name : 'Uzbek',
     tag : 'uz'},
    {name : 'Vietnamese',
     tag : 'vi'},
    {name : 'Welsh',
     tag : 'cy'},
    {name : 'Yiddish',
     tag : 'yi'},
    {name : 'Yoruba',
     tag : 'yo'},
    {name : 'Zulu',
     tag : 'zu'}
}